### ISSUE TITLE
How to solve this error!

### ISSUE THREAD

**Issue by ronygolderku** [josuemtzmo/EKE_SST_trends#19]
When executing the `sst_trends.compute() ` comand

it returns the error like the following..Do you have any suggestions?

```
2023-05-22 07:21:50,876 - distributed.protocol.pickle - ERROR - Failed to serialize <ToPickle: HighLevelGraph with 1 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x7efda0d52230>
 0. 139627919285376
>.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 63, in dumps
    result = pickle.dumps(x, **dump_kwargs)
TypeError: cannot pickle '_thread.lock' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 68, in dumps
    pickler.dump(x)
TypeError: cannot pickle '_thread.lock' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 81, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    * reducer_override has the priority over dispatch_table-registered
TypeError: cannot pickle '_thread.lock' object
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/miniconda3/lib/python3.10/site-packages/distributed/protocol/pickle.py:63, in dumps(x, buffer_callback, protocol)
     62 try:
---> 63     result = pickle.dumps(x, **dump_kwargs)
     64 except Exception:

TypeError: cannot pickle '_thread.lock' object

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
File ~/miniconda3/lib/python3.10/site-packages/distributed/protocol/pickle.py:68, in dumps(x, buffer_callback, protocol)
     67 buffers.clear()
---> 68 pickler.dump(x)
     69 result = f.getvalue()

TypeError: cannot pickle '_thread.lock' object

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
File ~/miniconda3/lib/python3.10/site-packages/distributed/protocol/serialize.py:350, in serialize(x, serializers, on_error, context, iterate_collection)
    349 try:
--> 350     header, frames = dumps(x, context=context) if wants_context else dumps(x)
    351     header["serializer"] = name

File ~/miniconda3/lib/python3.10/site-packages/distributed/protocol/serialize.py:73, in pickle_dumps(x, context)
     71     writeable.append(not f.readonly)
---> 73 frames[0] = pickle.dumps(
     74     x,
     75     buffer_callback=buffer_callback,
     76     protocol=context.get("pickle-protocol", None) if context else None,
     77 )
     78 header = {
     79     "serializer": "pickle",
     80     "writeable": tuple(writeable),
     81 }

File ~/miniconda3/lib/python3.10/site-packages/distributed/protocol/pickle.py:81, in dumps(x, buffer_callback, protocol)
     80     buffers.clear()
---> 81     result = cloudpickle.dumps(x, **dump_kwargs)
     82 except Exception:

File ~/miniconda3/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py:73, in dumps(obj, protocol, buffer_callback)
     70 cp = CloudPickler(
     71     file, protocol=protocol, buffer_callback=buffer_callback
     72 )
---> 73 cp.dump(obj)
     74 return file.getvalue()

File ~/miniconda3/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py:632, in dump(self, obj)
    607 def reducer_override(self, obj):
    608     """Type-agnostic reducing callback for function and classes.
    609 
    610     For performance reasons, subclasses of the C _pickle.Pickler class
    611     cannot register custom reducers for functions and classes in the
    612     dispatch_table. Reducer for such types must instead implemented in
    613     the special reducer_override method.
    614 
    615     Note that method will be called for any object except a few
    616     builtin-types (int, lists, dicts etc.), which differs from reducers
    617     in the Pickler's dispatch_table, each of them being invoked for
    618     objects of a specific type only.
    619 
    620     This property comes in handy for classes: although most classes are
    621     instances of the ``type`` metaclass, some of them can be instances
    622     of other custom metaclasses (such as enum.EnumMeta for example). In
    623     particular, the metaclass will likely not be known in advance, and
    624     thus cannot be special-cased using an entry in the dispatch_table.
    625     reducer_override, among other things, allows us to register a
    626     reducer that will be called for any class, independently of its
    627     type.
    628 
    629 
    630     Notes:
    631 
--> 632     * reducer_override has the priority over dispatch_table-registered
    633     reducers.
    634     * reducer_override can be used to fix other limitations of
    635       cloudpickle for other types that suffered from type-specific
    636       reducers, such as Exceptions. See
    637       https://github.com/cloudpipe/cloudpickle/issues/248
    638     """
    639     if sys.version_info[:2] < (3, 7) and _is_parametrized_type_hint(obj):  # noqa  # pragma: no branch

TypeError: cannot pickle '_thread.lock' object

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[34], line 1
----> 1 sst_trends.compute()

File ~/miniconda3/lib/python3.10/site-packages/xarrayMannKendall/decorators.py:91, in check_if_file_exists.<locals>.file_exists_inner(self, *args, **kwargs)
     89         return init(self, *args, **kwargs)
     90 else:
---> 91     return init(self, *args, **kwargs)

File ~/miniconda3/lib/python3.10/site-packages/xarrayMannKendall/xarrayMannKendall.py:210, in Mann_Kendall_test.compute(self, save, path, rewrite_trends, scheduler, progress_bar)
    208         MK_output = trend_method.compute(scheduler=scheduler)
    209 else:
--> 210     MK_output = trend_method.compute(scheduler=scheduler)
    212 if len(self.ordered_dims) == 2:
    213     ds = xr.Dataset({'trend': (['x'], MK_output[:,0]),
    214                  'signif': (['x'], MK_output[:,1]),
    215                  'p': (['x'], MK_output[:,2]),
    216                  'std_error': (['x'], MK_output[:,3])
    217                 },
    218                 coords={'x': (['x'], da2py(self.DataArray.x, False))})

File ~/miniconda3/lib/python3.10/site-packages/dask/base.py:314, in DaskMethodsMixin.compute(self, **kwargs)
    290 def compute(self, **kwargs):
    291     """Compute this dask collection
    292 
    293     This turns a lazy Dask collection into its in-memory equivalent.
   (...)
    312     dask.compute
    313     """
--> 314     (result,) = compute(self, traverse=False, **kwargs)
    315     return result

File ~/miniconda3/lib/python3.10/site-packages/dask/base.py:599, in compute(traverse, optimize_graph, scheduler, get, *args, **kwargs)
    596     keys.append(x.__dask_keys__())
    597     postcomputes.append(x.__dask_postcompute__())
--> 599 results = schedule(dsk, keys, **kwargs)
    600 return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

File ~/miniconda3/lib/python3.10/site-packages/distributed/client.py:3204, in Client.get(self, dsk, keys, workers, allow_other_workers, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   3131 def get(
   3132     self,
   3133     dsk,
   (...)
   3145     **kwargs,
   3146 ):
   3147     """Compute dask graph
   3148 
   3149     Parameters
   (...)
   3202     Client.compute : Compute asynchronous collections
   3203     """
-> 3204     futures = self._graph_to_futures(
   3205         dsk,
   3206         keys=set(flatten([keys])),
   3207         workers=workers,
   3208         allow_other_workers=allow_other_workers,
   3209         resources=resources,
   3210         fifo_timeout=fifo_timeout,
   3211         retries=retries,
   3212         user_priority=priority,
   3213         actors=actors,
   3214     )
   3215     packed = pack_data(keys, futures)
   3216     if sync:

File ~/miniconda3/lib/python3.10/site-packages/distributed/client.py:3103, in Client._graph_to_futures(self, dsk, keys, workers, allow_other_workers, internal_priority, user_priority, resources, retries, fifo_timeout, actors)
   3100 from distributed.protocol import serialize
   3101 from distributed.protocol.serialize import ToPickle
-> 3103 header, frames = serialize(ToPickle(dsk), on_error="raise")
   3104 nbytes = len(header) + sum(map(len, frames))
   3105 if nbytes > 10_000_000:

File ~/miniconda3/lib/python3.10/site-packages/distributed/protocol/serialize.py:372, in serialize(x, serializers, on_error, context, iterate_collection)
    370     return {"serializer": "error"}, frames
    371 elif on_error == "raise":
--> 372     raise TypeError(msg, str(x)[:10000]) from exc
    373 else:  # pragma: nocover
    374     raise ValueError(f"{on_error=}; expected 'message' or 'raise'")

TypeError: ('Could not serialize object of type HighLevelGraph', '<ToPickle: HighLevelGraph with 1 layers.\n<dask.highlevelgraph.HighLevelGraph object at 0x7efda0d52230>\n 0. 139627919285376\n>')
```

**Comment by josuemtzmo** [comment]
Hello @ronygolderku,
This seems to be an issue with the libraries `dask`, `xarray`, and/or `xarrayMannKendall` or the chunking of your dataset. I will recommend you to do a fresh reinstall of the libraries and retry. If the issue persists, I will recommend you to post a more detailed description of the data, RAM, and libraries versions within the `xarrayMannKendall` repository. I'm closing the issue.
